@startuml
'https://plantuml.com/class-diagram


interface flayable{
+fly():
}
class bird.Bird{
-weight:Double
-color: String

}
class Eagle implements flayable{

}
class Hen extends bird.Bird implements flayable{
}
class kiwi extends bird.Bird{
}

class Mi_21 implements flayable{
}
class saktiman implements flayable{
}
class Game {
+void render(bird.Bird b){
b.fly()
}

bird.Bird <|-- Eagle






@enduml